// To be included

@def SYSCALL_EXIT 60
@def SYSCALL_READ 0
@def SYSCALL_WRITE 1
@def SYSCALL_CLOSE 3
@def SYSCALL_LSEEK 8
@def SYSCALL_SOCKET 41
@def SYSCALL_CONNECT 42

@def SYS_AF_UNIX 1
@def SYS_SOCK_STREAM 1

@def FIO_SEEK_SET 0
@def FIO_SEEK_CUR 1
@def FIO_SEEK_END 2
